-- local builtin = require('telescope.builtin')
-- vim.keymap.set('n', '<leader>ff', builtin.find_files)
--vim.keymap.set('n', '<leader>fg', builtin.live_grep)
-- vim.keymap.set('n', '<leader>fb', builtin.buffers)
-- vim.keymap.set('n', '<leader>fh', builtin.help_tags)
-- vim.keymap.set("n", "<leader>pv", vim.cmd.Ex)
-- vim.keymap.set('n', '<leader>t', '<Cmd>NvimTreeToggle<CR>')
local map = vim.keymap.set
map('n', '<leader>ff', '<Cmd>Telescope find_files<CR>')
map('n', '<leader>fg', '<Cmd>Telescope live_grep<CR>')
map('n', '<leader>fb', '<Cmd>Telescope buffers<CR>')
map('n', '<leader>fh', '<Cmd>Telescope help_tags<CR>')
map("n", "<leader>pv", '<Cmd>Ex<CR>')
map('n', '<leader>t', '<Cmd>NvimTreeToggle<CR>')
